image_root_url: http://res.cloudinary.com/ppls/image/upload/
image_account : peoplesizedcom/

host: 0.0.0.0
permalink: /:year/:title.html
gems:
  - jekyll-coffeescript
  - jekyll-sitemap
exclude:
  - node_modules
title: Peoplesized
email: hello@peoplesized.com
description: Peoplesized build and manage good things for the environment and social development.
keywords: 
  - environment
  - social development
  - technology
  - software
baseurl: "" # the subpath of your site, e.g. /blog/


url: "http://www.peoplesized.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
exclude: 
  - _data

prose:
  rooturl: _posts
