image_root_url: http://res.cloudinary.com/ppls/image/upload/
image_account : peoplesizedcom/

permalink: /:year/:title.html
exclude:
  - node_modules
  - gulpfile.coffee
  - package.json
gems:
  - jekyll-coffeescript
title: Peoplesized
email: hello@peoplesized.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/


url: "http://www.peoplesized.com" # the base hostname & protocol for your site
github_username:  onlyjsmith
# Build settings
markdown: kramdown
exclude: 
  - _data

prose:
  rooturl: _posts
  
