image_root_url: http://res.cloudinary.com/ppls/image/upload/
image_account : peoplesizedcom/

host: 0.0.0.0
permalink: /:year/:title.html
gems:
  - jekyll-coffeescript
  - jekyll-sitemap
exclude:
  - node_modules
title: Peoplesized
email: hello@peoplesized.com
description: Peoplesized build and manage good things for the environment and social development.
keywords: 
  - environment
  - social development
  - technology
  - software
  - policy
  - research
  - analysis
baseurl: ""


url: "http://www.peoplesized.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
exclude: 
  - _data

prose:
  rooturl: _posts
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: website
        field:
          element: text
          placeholder: Full URL (incl. "http://")
          label: Website or link for project
      - name: status
        field:
          label: Status
          element: select 
          options:
            - name: Concept
              value: concept
            - name: In development
              value: in_development
            - name: Live
              value: live
            - name: Complete
              value: complete
      - name: dateCompleted
        field:
          element: text
          placeholder: YYYY-MM-DD
          label: Date - either completed, expected or last update
      - name: imageUrl
        field:
          element: text
          placeholder: Cloudinary image url
          label: Image URL (Cloudinary)
      - name: layout
        field:
          element: text
          value: post
          label: Layout
