image_root_url: http://res.cloudinary.com/ppls/image/upload/
image_account : peoplesizedcom/

host: 0.0.0.0
permalink: /:year/:title.html
gems:
  - jekyll-coffeescript
  - jekyll-sitemap
exclude:
  - node_modules
title: Peoplesized
email: hello@peoplesized.com
description: Peoplesized build and manage good things for the environment and social development.
keywords: 
  - environment
  - social development
  - technology
  - software
  - policy
  - research
  - analysis
baseurl: ""


url: "http://www.peoplesized.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
exclude: 
  - _data

prose:
  rooturl: _posts
  _posts:
    - name: "title"
      field:
        element: "text"
        label: "title"
    - name: layout
      field:
        element: text
        value: post
    - name: website
      field:
        element: text
        placeholder: Full URL (incl. "http://")
    - name: status
      field:
        element: 
        options:
          - name: Concept
          - name: In development
          - name: Live
          - name: Complete
        value:
    - name: dateCompleted
      field:
        element: text
        placeholder: YYYY-MM-DD
    - name: imageUrl
      field:
        element: text
        placeholder: Cloudinary image url
